# Generated by Django 4.2.4 on 2023-08-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_card',
            field=models.ImageField(upload_to='movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_review',
            field=models.TextField(),
        ),
    ]
