# Generated by Django 4.2.4 on 2023-08-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_movie_movie_card_alter_movie_movie_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_review',
            new_name='movie_details',
        ),
    ]
